language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: Eda6Myle5reef+akN6H/2h0FUgKPIc2CYmT7uGayBKBg0ie0jpXr53bep8tOSZGsXQWo3I44gFK5A+j71gWhlp1g8cQ7Z4cP17uUM2hmvLEVZDJ+iITlEpCAqeE5oWiVFiFUu41w817spflhKrdTESVF2MKLi3q4iR07HwSLu2l8wqVXL0lSBX6VoR9v94yHwrBQ4cDgs/YPkOC7o5lWgx5NSpDTogV/7Z0D+8LW9p+SmVN7R3C9R8RoW8zK0x0zCo/YCXgTtZlXDaAGBNYFupXItYVhdUwCVU/OcFO62kvRaOsxr2PNXsZjYQCglyfcTF/aqaiZwA2EqOusIUY3h3Qug83Eh9WqXrxlMAhx3tvT4/8otwRJ277bjeBZTk+1zPY86Pg2FSXGG8vIbeC5AaXwySiRPPPxUN27CuUeKrBq52hkdgm6zRLx3J4/9QZ+ad75lnGPkiQRZVjb18nsZvsAw+XkCzh131J/yJO7fdbwMkYquHdu2hN9fM+LlrZqn3NdmWjLImFJa4fSlDi7UjjKLvutVBJsAVEZ5ruw6HN9d+Impd6DzMgkYy2TJecCwwUp+JkyliuRVFmKL1MXqBlBMkgjq2QtDvxtsIQ0m9UM1/ClrD1HIqVTXIbaQ/2kgdZljiNfsm1MWpNL+AYWco9E2Zzmj/N+tqCiy/2054o=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
 - provider: firebase
   skip_cleanup: true
   on:
     branch: master      # on which branch trigger build
   project: cs3-krakow-2018   # Firebase project name
   token:
     secure: "WOWlYoP2PZvnXyjuN5cI2mhTOyuVebTNpTv4uxWGq1iMDTJscOU9OJ33aQot1LlSPBj+3R0riruhLjMwOafFi22sLKJjEWP0PJBtBjMy8sD69OBplNBB3sWxA6rfOThggL3rOpHDxZ2lJJL2bif80KNWpkHe/TUHJD15LAQtqKfraqfTj9YFQzUi3FfeAca/bVNOtmKtyR/Ai3ViUjtcrCGAWwTTVCLFurbBMFdYnResZkBWiBEm70vZCYvULDqLAP8go39XcPxPvvRQ5+F5dmkrfWhu+j09F1RqEcPxrV7V0TNt2XSavHN+K+uw002eJUFGPanwSKoDkAm50r60rFxbC57r5c0KhWeaLc52apgFosX2zsGs2Ezl+TOvtTkgdUK0pwdVkPn7Z2E4t8Rvu6ebQmzbk+fOcRSfrqbK4sZNtRDkLq/g5G1kAeYPX6+ObR3h8mAtJaka9FrZ70/qmYvBaukNvpdFFkTZhJBzXiiwrko1zCNalOQCY+jkyY2LYxTFO9shAZ2xYwag+XFLiC9sbDOPT0spCiUcgywdqcfFfr7T5m7ZqqGliDXU1aYx2uGUMGRe6eQt3jj0pEM3bYqHzV6lN5n9QaQlYz7aVODCc7uaC7w7eMyQsKiAhGTtR3CJvubbSGZ0Ame6VZGVKDp/wJHIiwBFx/n1I5H+uOY="